spring:
  profiles:
    active: dev
---
spring:
  profiles: dev
  application:
    name: microservicecloud-config-client
server:
  port: 8201

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: microservicecloud-config-client8201

---
spring:
  profiles: test
  application:
    name: microservicecloud-config-client
server:
  port: 8202

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: microservicecloud-config-client8202